const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});try{
 const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});
 const plain=await nojs.newPage();await plain.goto('http://127.0.0.1:4173');
 await plain.getByRole('heading',{name:'How to play Anagramish',exact:true}).waitFor();
 assert.match(await plain.locator('main').innerText(),/Each step must be a valid 5-letter word/);
 await plain.getByRole('link',{name:'Read the rules and see a worked example'}).click();
 await plain.getByRole('heading',{level:1,name:'How to play Anagramish'}).waitFor();
 assert.equal(await plain.locator('.guide-ladder li').count(),6);
 assert.equal(await plain.locator('link[rel="canonical"]').getAttribute('href'),'https://anagramish.com/how-to-play.html');
 assert.equal(await plain.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await plain.screenshot({path:'/tmp/anagramish-rules-mobile.png',fullPage:true});
 const context=await browser.newContext();const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:4173/how-to-play.html',{referer:'https://www.google.com/search?q=anagram+word+ladder'});
 await page.waitForFunction(()=>sessionStorage.getItem('anagramish-acquisition-v1'));
 await page.getByRole('link',{name:'Play Anagramish',exact:true}).click();
 await page.getByRole('button',{name:'Learn to play',exact:true}).waitFor();
 const start=page.waitForRequest(r=>r.url().endsWith('/api/start'));
 await page.getByRole('button',{name:'Practice',exact:true}).click();
 const attribution=(await start).postDataJSON().attribution;
 assert.deepEqual(attribution,{source:'google',medium:'organic',campaign:null,referrer:'https://www.google.com',landing:'/how-to-play.html'});
 await page.waitForSelector('.board .current');
 await page.getByRole('button',{name:'Home',exact:true}).click();await page.getByRole('button',{name:'Learn to play',exact:true}).click();
 await page.keyboard.type('cot');await page.keyboard.press('Enter');await page.getByText('Now type DOT.',{exact:false}).waitFor();
 await page.goto('http://127.0.0.1:4173/?utm_source=newsletter&utm_medium=email&utm_campaign=launch');
 const tagged=await page.evaluate(async()=>{const {getAttribution}=await import('/acquisition.mjs');return getAttribution()});
 assert.equal(tagged.source,'newsletter');assert.equal(tagged.medium,'email');
 assert.deepEqual(errors,[]);
 console.log('SEO browser passed: readable without JavaScript, linked static rules, mobile layout, preserved organic entry source, campaign priority, and normal game/tutorial navigation.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
